source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               schema/,\
               lib/,\
               .
jars.extra.classpath = lib/mcp-core-1.1.2.jar,\
                       lib/mcp-json-jackson2-1.1.2.jar,\
                       lib/reactor-core-3.7.0.jar,\
                       lib/reactive-streams-1.0.4.jar,\
                       lib/json-schema-validator-2.0.0.jar,\
                       lib/itu-1.14.0.jar,\
                       lib/jackson-core-2.20.1.jar,\
                       lib/jackson-databind-2.20.1.jar,\
                       lib/jackson-annotations-2.20.jar,\
                       lib/jackson-dataformat-yaml-2.18.3.jar,\
                       lib/snakeyaml-2.3.jar,\
                       lib/jakarta.servlet-api-6.1.0.jar,\
                       lib/jetty-server-12.0.13.jar,\
                       lib/jetty-http-12.0.13.jar,\
                       lib/jetty-io-12.0.13.jar,\
                       lib/jetty-util-12.0.13.jar,\
                       lib/jetty-security-12.0.13.jar,\
                       lib/jetty-session-12.0.13.jar,\
                       lib/jetty-ee10-servlet-12.0.13.jar
